import { findBlock } from './merge.ts'

/**
 * What `rness hook pre-tool-use` decides before Claude Code writes a file
 * (spec 0029 §4): pure functions over the file's text and the tool's input.
 */

/** A file's text as an `Edit` or a `Write` would leave it. */
export interface Replayed {
  after: string
  /** The character ranges of the text the edit replaces; the whole file for a `Write`. */
  spans: readonly (readonly [number, number])[]
}

/**
 * An `Edit` replayed as the tool does it: every occurrence under
 * `replace_all`, else exactly one. Null when the tool would refuse it
 * (nothing found, found twice, an empty `old_string`): it fails on its own.
 */
export function replayEdit(
  text: string,
  oldString: string,
  newString: string,
  all: boolean
): Replayed | null {
  if (oldString === '') return null
  const spans: [number, number][] = []
  for (
    let i = text.indexOf(oldString);
    i !== -1;
    i = text.indexOf(oldString, i + oldString.length)
  )
    spans.push([i, i + oldString.length])
  if (spans.length === 0 || (!all && spans.length !== 1)) return null
  return { after: text.split(oldString).join(newString), spans }
}

/** The whole files rness writes in a project directory (spec 0016 §3.2). */
const OWNED = /(?:^|\/)\.claude\/skills\/rness\//

/** Whether a workspace-relative path is one of rness's whole files. */
export const ownedWhole = (rel: string): boolean => OWNED.test(rel)

export function ownedRefusal(label: string): string {
  return `rness: ${label} is written whole by rness sync, and the next sync overwrites it. Leave it to rness.`
}

const MARKER = /^<!-- rness: (\S+) -->$/

interface Block {
  /** Line indexes, inclusive. */
  begin: number
  end: number
  /** Character offsets: the first of BEGIN, the one after END. */
  from: number
  to: number
  lines: string[]
}

function blockOf(text: string): Block | null {
  const lines = text.split(/\r?\n/)
  const found = findBlock(lines)
  if (found.kind !== 'one') return null
  const starts = [0]
  for (const m of text.matchAll(/\r?\n/g))
    starts.push((m.index ?? 0) + m[0].length)
  const from = starts[found.begin] ?? 0
  const to = (starts[found.end] ?? 0) + (lines[found.end] ?? '').length
  return { begin: found.begin, end: found.end, from, to, lines }
}

/** The line of a character offset. */
function lineAt(text: string, offset: number): number {
  return text.slice(0, offset).split(/\r?\n/).length - 1
}

/** The source of a block's line: the nearest rule marker above it in the block. */
function sourceOf(block: Block, line: number): string {
  for (let i = Math.min(line, block.end); i > block.begin; i--) {
    const m = MARKER.exec((block.lines[i] ?? '').trimEnd())
    if (m !== null) return `.rness/${m[1] ?? ''}`
  }
  return '.rness/ and rness.json'
}

function blockRefusal(label: string, block: Block, source: string): string {
  return `rness: lines ${block.begin + 1}–${block.end + 1} of ${label} are generated by rness sync from ${source}. Edit that file, then run rness sync.`
}

/**
 * Why an `Edit` of a file holding the block is refused: one of the ranges it
 * replaces overlaps the block. Null when it leaves the block alone, or when
 * the file has no block (or a broken one, which `sync` reports).
 */
export function editRefusal(
  label: string,
  before: string,
  spans: Replayed['spans']
): string | null {
  const block = blockOf(before)
  if (block === null) return null
  const hit = spans.find(([s, e]) => s < block.to && e > block.from)
  if (hit === undefined) return null
  return blockRefusal(
    label,
    block,
    sourceOf(block, lineAt(before, Math.max(hit[0], block.from)))
  )
}

/**
 * Why a `Write` of a file holding the block is refused: the block is not in
 * the new text byte for byte. The source named is that of the first line
 * that differs.
 */
export function writeRefusal(
  label: string,
  before: string,
  after: string
): string | null {
  const block = blockOf(before)
  if (block === null) return null
  const kept = blockOf(after)
  const was = before.slice(block.from, block.to)
  if (kept !== null && after.slice(kept.from, kept.to) === was) return null
  const next = kept === null ? [] : kept.lines.slice(kept.begin, kept.end + 1)
  const old = block.lines.slice(block.begin, block.end + 1)
  const first = old.findIndex((line, i) => line !== next[i])
  return blockRefusal(
    label,
    block,
    kept === null
      ? '.rness/ and rness.json'
      : sourceOf(block, block.begin + Math.max(first, 0))
  )
}
