export { run } from './cli.ts'
export { VERSION } from './version.ts'
export { contextCommand, renderMarkdown, type ContextOptions } from './commands/context.ts'
export { validateCommand, type ValidateOptions } from './commands/validate.ts'
export { reportError } from './report.ts'
export { parseFrontMatter, extractTitle } from './core/frontmatter.ts'
export { collectMarkdown } from './core/collect.ts'
export { loadManifest, NAME } from './core/manifest.ts'
export { findWorkspace } from './core/workspace.ts'
export { resolveScope, scopeChain } from './core/scope.ts'
export { assembleContext, COLLECTIONS, type AssembleInput } from './core/context.ts'
export { checkContract, STATUSES } from './core/contract.ts'
export { scaffoldDir, SCAFFOLD_FILES } from './core/scaffold.ts'
export type * from './core/types.ts'
